version: "3"

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: $WIREGUARD_CONTAINER
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - SERVERURL=$SERVER_IP
      - SERVERPORT=51820
      - PEERS=$WIREGUARD_PEERS
      - PEERDNS=auto
      - INTERNAL_SUBNET=$WIREGUARD_INTERNAL_SUBNET
    ports:
      - 51820:51820/udp
    volumes:
      - ./volumes/wireguard/config:/config
      - ./Corefile:/config/coredns/Corefile
      - /lib/modules:/lib/modules
    restart: always
    networks:
      network:
        ipv4_address: "${SUBNET}2"
    depends_on:
      - pihole
      - dnscrypt-proxy

  pihole:
    image: pihole/pihole:latest
    container_name: $PIHOLE_CONTAINER
    domainname: $PIHOLE_DOMAIN
    hostname: pihole
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=$TZ
      - WEBPASSWORD=$PIHOLE_PASSWORD
      - DNS1=${SUBNET}4#${DNSCRYPT_PORT}
      - DNS2=no
      - DNSSEC=$DNSSEC
    ports:
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
      - "${PIHOLE_PORT}:80/tcp"
    volumes:
      - ./volumes/pihole/etc-pihole:/etc/pihole
      - ./volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: always
    networks:
      network:
        ipv4_address: "${SUBNET}3"
    depends_on:
      - dnscrypt-proxy

  dnscrypt-proxy:
    image: gists/dnscrypt-proxy:latest
    container_name: $DNSCRYPT_CONTAINER
    ports:
      - "${DNSCRYPT_PORT}:5353/tcp"
      - "${DNSCRYPT_PORT}:5353/udp"
    volumes:
      - ./dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml
    restart: always
    networks:
      network:
        ipv4_address: "${SUBNET}4"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "${SUBNET}0/${SUBNET_MASK}"
