version: "3.8"

services:
    wireguard:
        image: linuxserver/wireguard:latest
        container_name: $WIREGUARD_CONTAINER
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$TZ
            - SERVERURL=$SERVER_IP
            - SERVERPORT=51820
            - PEERS=$WIREGUARD_PEERS
            - PEERDNS=auto
            - INTERNAL_SUBNET=$WIREGUARD_INTERNAL_SUBNET
        volumes:
            - ./volumes/wireguard/config:/config
            - ./volumes/wireguard/modules:/lib/modules
        ports:
            - 51820:51820/udp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
        networks:
            wireguard:
                ipv4_address: "${SUBNET}2"
        depends_on:
            - pihole

    pihole:
        image: pihole/pihole:latest
        container_name: $PIHOLE_CONTAINER
        domainname: $PIHOLE_DOMAIN
        hostname: pihole
        ports:
            - "${SERVER_IP}:53:53/tcp"
            - "${SERVER_IP}:53:53/udp"
            - "${PIHOLE_PORT}:80/tcp"
        environment:
            - ServerIP=$SERVER_IP
            - TZ=$TZ
            - WEBPASSWORD=$PIHOLE_PASSWORD
            - DNS1=$PIHOLE_DNS1#53
            - DNS2=$PIHOLE_DNS2
        volumes:
            - ./volumes/pihole/etc-pihole:/etc/pihole
            - ./volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
        networks:
            wireguard:
                ipv4_address: "${SUBNET}3"

networks:
    wireguard:
        ipam:
            driver: default
            config:
                - subnet: "${SUBNET}0/${SUBNET_MASK}"
